// Generated by CoffeeScript 1.9.3
(function() {
  var x, y, z;

  x = [1, 2, 4];

  y = 2 * x + 10;

  z = Math.sqrt(x + 1);

  x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  y = [10, 9, 8, 7, 6, 5];

  z = numeric.linspace(-1, 1, 5);

}).call(this);
