// Generated by CoffeeScript 1.9.3
(function() {
  $combnk = function(n, k) {
    var combo, combos, i;
    if (k === 0) {
      return [[]];
    }
    i = 0;
    combos = [];
    combo = [];
    while (combo.length < k) {
      if (i < n) {
        combo.push(i);
        i += 1;
      } else {
        if (combo.length === 0) {
          break;
        }
        i = combo.pop() + 1;
      }
      if (combo.length === k) {
        combos.push(combo.clone());
        i = combo.pop() + 1;
      }
    }
    return combos;
  };

}).call(this);
